appname: "GuArt"
template: "template_toolkit"
layout: "main"
session: "Simple"

# only log warning and error messages
logger: "file"
engines:
  logger:
    File:
      file_name: "art.log"
      log_dir:   "log"
      log_level: "debug"
